GDevelopApp/GDevelop-documentation

docs/gdevelop5/extensions/fire-bullet/details.md
https://gdevelop-wiki-git-fire-bullet-typo-gdevelop.vercel.app/gdevelop5/extensions/fire-bullet/details/
=> [Fire bullet] Fix typo

docs/gdevelop5/objects/text_input.md
=> Improving the text input object page.

docs/gdevelop5/objects/particles_emitter.md
Just had to remove a line that had // on either end. Replaced with **.
=> Quick fix for " //" that were on this page.

docs/gdevelop5/all-features/gamepad.md
=> Add a new action with customized vibration

docs/gdevelop5/tutorials/piskel-sprite-sheets.md
Trying to fix numbered lists importing.
=> Update piskel sprite sheet tutorial

docs/gdevelop5/extensions/share.md
https://gdevelop-wiki-git-share-extension-gdevelop.vercel.app/gdevelop5/extensions/share/#ensure-your-extension-follow-the-best-practices
=> [Share extension] Add a link and fix some typo

README.md, docs/gdevelop5/events/functions/index.md, docs/gdevelop5/extensions/.pages, docs/gdevelop5/extensions/create.md, docs/gdevelop5/extensions/index.md
- Simplify some stuff
- Add references of parameters types
- Explain what is for the Identifier parameter.
=> Update extensions pages

docs/gdevelop5/tutorials/resources.md
Adding Atlasicons for gamedev creators.
=> Adding Atlasicons

docs/gdevelop5/objects/slider.md
=> Improving the slider object page.

docs/gdevelop5/objects/shape_painter.md
=> Improving the shape painter object page.

docs/gdevelop5/objects/bitmap_text.md
=> Improving the bitmap text object page.

docs/gdevelop5/objects/toggle-switch.md
=> Improving the Toggle Switch object page.

CONTRIBUTE.md, README.md, SYNTAX.md, docs/de/index.md, docs/gdevelop5/about_translations.md, docs/gdevelop5/index.md, mkdocs.yml
Change the wording wiki -> documentation on the documentation, to be consistent with the contribution page on the website, and with the fast that is not a wiki anymore but an open documentation.
=> Change wording

docs/gdevelop5/objects/3d-model/index.md
https://gdevelop-wiki-git-3d-asset-sources-gdevelop.vercel.app/gdevelop5/objects/3d-model/#performance-considerations
=> Add a link to Quaternius 3D assets

docs/gdevelop5/behaviors/events-based-behaviors/index.md, docs/gdevelop5/events/functions/index.md, docs/gdevelop5/tutorials/how-to-make-behavior.md
https://gdevelop-wiki-git-extension-pages-link-gdevelop.vercel.app/gdevelop5/behaviors/events-based-behaviors
https://gdevelop-wiki-git-extension-pages-link-gdevelop.vercel.app/gdevelop5/events/functions
https://gdevelop-wiki-git-extension-pages-link-gdevelop.vercel.app/gdevelop5/tutorials/how-to-make-behavior
=> Add links between pages about event-based extensions

.circleci/config.yml
=> Fix CI skip command and Upgrade Docker image to next-gen CircleCI image

docs/gdevelop5/events/functions/index.md, docs/gdevelop5/events/js-code/index.md
@D8H 
Related to your addition in : https://github.com/4ian/GDevelop/pull/5559/files
=> Add docs about new parameters for resources

docs/gdevelop5/all-features/linked-objects/index.md
https://gdevelop-wiki-git-fix-linked-object-examples-gdevelop.vercel.app/gdevelop5/all-features/linked-objects/#examples
=> [Linked objects] Fix example names

docs/gdevelop5/events/js-code/index.md
https://gdevelop-wiki-git-js-and-extension-gdevelop.vercel.app/gdevelop5/events/js-code/#learn-by-reading-code-from-the-community
=> [JS code] Add JS-based extension links

docs/gdevelop5/events/js-code/index.md
https://gdevelop-wiki-git-js-examples-gdevelop.vercel.app/gdevelop5/events/js-code/#learn-by-reading-code-from-the-community
=> [JS code] Add 2 more extension examples

docs/gdevelop5/tutorials/how-to-make-behavior/index.md
https://gdevelop-wiki-git-behavior-tuto-links-gdevelop.vercel.app/gdevelop5/tutorials/how-to-make-behavior/
=> [How to make a behavior] Use relative links for images

docs/gdevelop5/all-features/advanced-conditions/index.md, docs/gdevelop5/events/foreach/index.md
https://gdevelop-wiki-git-fix-for-each-warn-gdevelop.vercel.app/gdevelop5/events/foreach/
https://gdevelop-wiki-git-fix-for-each-warn-gdevelop.vercel.app/gdevelop5/all-features/advanced-conditions/#trigger-once
=> [For each] Clarify the warning about trigger once

docs/gdevelop5/behaviors/events-based-behaviors/index.md
https://gdevelop-wiki-git-custom-behavior-gdevelop.vercel.app/gdevelop5/behaviors/events-based-behaviors/
- Remove uninformative sentences
- Add some explanations to introduce some concepts with simple terms
I have been very conservative because I'm waiting for the new UI to take new screenshots and replace the examples.
=> [Custom behaviors] Add some explanations

docs/gdevelop5/behaviors/events-based-behaviors/index.md
This PR is to open the discussion.
=> [Custom behaviors] Slight rewording

docs/gdevelop5/all-features/firebase/quickstart.md
Fix formatting
Reword a few things
=> Improve firebase getting started page

docs/gdevelop5/interface/scene-editor/external-layouts.md
This problem is described here: https://github.com/4ian/GDevelop/issues/3571
=> Add note about object picking on objects created by an external layout

docs/gdevelop5/interface/games-dashboard/index.md
Update text for game dashboard.
=> Update game dashboard.md

docs/gdevelop5/.pages, docs/gdevelop5/education/index.md
[Added page](https://gdevelop-wiki-git-education-account-gdevelop.vercel.app/gdevelop5/education/)
=> Add page about education plan

docs/gdevelop5/all-features/expressions/index.md, docs/gdevelop5/all-features/resources-loading/index.md, docs/gdevelop5/all-features/timers-and-time/index.md, docs/gdevelop5/behaviors/physics2/index.md, docs/gdevelop5/behaviors/platformer/index.md, docs/gdevelop5/behaviors/topdown/index.md, docs/gdevelop5/behaviors/tween/index.md, docs/gdevelop5/interface/scene-editor/layers-and-cameras.md, docs/gdevelop5/objects/index.md, docs/gdevelop5/objects/particles_emitter/index.md, docs/gdevelop5/objects/sprite/index.md, docs/gdevelop5/publishing/index.md
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/publishing/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/all-features/resources-loading/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/objects/#learn-about-some-objects-with-this-video-tutorial
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/behaviors/tween/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/all-features/timers-and-time/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/objects/sprite/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/interface/scene-editor/layers-and-cameras/
- https://gdevelop-wiki-git-add-video-link-gdevelop.vercel.app/gdevelop5/all-fea …
=> Add some video links

docs/gdevelop5/tutorials/asteroids/fail_state.md, docs/gdevelop5/tutorials/asteroids/firing_bullet.md, docs/gdevelop5/tutorials/asteroids/screen_wrap.md, docs/gdevelop5/tutorials/breakout/index.md, docs/gdevelop5/tutorials/geometry-monster/10-more-lives.md, docs/gdevelop5/tutorials/geometry-monster/12-main-menu.md, docs/gdevelop5/tutorials/geometry-monster/4-desktop-and-mobile-controls.md, docs/gdevelop5/tutorials/platformer/part-4.md, docs/gdevelop5/tutorials/platformer/part-8.md, docs/gdevelop5/tutorials/space-shooter/2-move-player.md, docs/gdevelop5/tutorials/topdown-shooter/topdown-shooterpart2.md
https://gdevelop-wiki-git-tutorial-warn-gdevelop.vercel.app/gdevelop5/tutorials/
=> Add warning to suggest behaviors in tutorials

docs/gdevelop5/extensions/best-practices.md
https://gdevelop-wiki-git-extension-best-practices-gdevelop.vercel.app/gdevelop5/extensions/best-practices/
=> [Extension best practices] Simplify and update a few things

docs/gdevelop5/interface/ai/agent/index.md
Update allowance of free AI allocation with agent based on pricing page.
=> Update allowance of free AI allocation with agent

docs/gdevelop5/events/js-code/index.md
https://gdevelop-wiki-git-object-classes-gdevelop.vercel.app/gdevelop5/events/js-code/#change-animation-according-to-some-conditions-on-the-behavior-of-an-object
=> [JS event] Add link to the list of objects and behaviors sub-classes
